test_format = 1.0

[default]

exclude = [ "change_url" ]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

  # test_upgrade_from.aa1c6c9.name = "Upgrade from v0.11.9"
